### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by LCRONG** [georgique/yii2-jsonrpc#6]
You want to replace the request URL and path info, but why set null in the `setPathInfo()` method?

In the JsonRpcRequest.php file
` // Replacing requested URL and path info
            $app->request->setUrl($route);
            $app->request->setPathInfo(null);`

**Comment by georgique** [comment]
Honestly I don't remember. What is exactly the problem though?

**Comment by georgique** [comment]
I've worked on this recently, and now set BaseUrl to null as well. Reason for this is that when we execute JsonRpcRequest, it's internal one, and previous pathinfo and baseurl are actually incorrect for it. I'm pretty sure baseurl should be set to null, but not so sure about pathinfo, it looks like it should be changed to the internal method.
